version: '3.9'

services:
  db:
    container_name: somemysql
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: restdb
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: restadmin
      MYSQL_PASSWORD: password

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 3310
